management:
  endpoints:
    web:
      path-mapping:
        info: version
      exposure:
        include: health,info
      base-path: /
info:
  version: 0.0.1

aws:
  region: sa-east-1
  access-key: KEY
  secret-access-key: SECRET
  dynamodb:
    endpoint: dynamodb.sa-east-1.amazonaws.com
